# update-module-version.ps1 — keeps a module's version metadata in sync with
# one number you type once, without needing module-builder (which is
# PracSim-internal and never ships). Self-contained: copy this file anywhere
# alongside a *DLL/ project and it works.
#
# Run it BEFORE compiling (build-module.bat calls this automatically when you
# pass it a version -- see "scripts\build-module.bat 26.1.3"):
#   powershell -File scripts\update-module-version.ps1 -Version 26.1.3
#
# What it does, each skipped gracefully ("if it exists") when not applicable:
#   1. Writes <Name>DLL\generated\pracsim_version.h -- #define PRACSIM_MODULE_VERSION
#      "26.1.3". Only useful once your module.cpp does
#      #include "generated/pracsim_version.h" and passes PRACSIM_MODULE_VERSION
#      to psslm::registerModule(...) instead of a hand-typed string.
#   2. Updates <Name>.fsx's release / revision / "flexsim release" nodes
#      (release = "flexsim release" = "X.Y", revision = ".Z").
#
# IMPORTANT: this only edits the SOURCE .fsx. FlexSim modules ship the
# COMPILED .t file, never the .fsx. After this script changes the .fsx, you
# must open FlexSim, load the module, and click File > Save Default to
# regenerate .t from it -- skipping that ships a module whose behaviour
# still matches the OLD .fsx even though the version metadata "changed".

[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $Version
)

$ErrorActionPreference = 'Stop'

if ($Version -notmatch '^(\d+)\.(\d+)\.(\d+)$') {
    throw "ERROR: version '$Version' must be X.Y.Z (e.g. 26.1.3)."
}
$release  = "$($Matches[1]).$($Matches[2])"
$revision = ".$($Matches[3])"

# Module root = this script's parent's parent (scripts\update-module-version.ps1 -> ModuleRoot\).
$moduleRoot = Split-Path -Parent $PSScriptRoot

# --- 1. DLL version header -------------------------------------------------
$dllDir = Get-ChildItem -Path $moduleRoot -Directory -Filter '*DLL' -ErrorAction SilentlyContinue | Select-Object -First 1
if ($dllDir) {
    $name = $dllDir.Name.Substring(0, $dllDir.Name.Length - 3)   # strip trailing "DLL"
    $generatedDir = Join-Path $dllDir.FullName 'generated'
    if (-not (Test-Path $generatedDir)) { New-Item -ItemType Directory -Path $generatedDir -Force | Out-Null }
    $headerPath = Join-Path $generatedDir 'pracsim_version.h'
    $headerContent = @"
// GENERATED by scripts\update-module-version.ps1 -- do not hand-edit.
// Regenerate with: powershell -File scripts\update-module-version.ps1 -Version X.Y.Z
#pragma once
#define PRACSIM_MODULE_VERSION "$Version"
"@ + "`r`n"
    [IO.File]::WriteAllText($headerPath, $headerContent, [Text.UTF8Encoding]::new($false))
    Write-Host "[update-module-version] wrote $headerPath (PRACSIM_MODULE_VERSION `"$Version`")"
    Write-Host "[update-module-version] rebuild the DLL now for this to take effect -- module-builder cannot compile it for you."
} else {
    Write-Host "[update-module-version] no *DLL folder found under $moduleRoot -- skipping version header."
}

# --- 2. .fsx release / revision / flexsim release metadata -----------------
$fsxCandidates = Get-ChildItem -Path $moduleRoot -Filter '*.fsx' -File -ErrorAction SilentlyContinue
$fsxPath = $fsxCandidates | Select-Object -First 1
if ($fsxPath) {
    $text = [IO.File]::ReadAllText($fsxPath.FullName)
    if ($text -match '<name>release</name>') {
        function Set-FsxNode([string]$Text, [string]$NodeName, [string]$Value) {
            $pattern = "(<name>$([regex]::Escape($NodeName))</name><data>)([^<]*)(</data>)"
            $found = [regex]::Matches($Text, $pattern)
            if ($found.Count -ne 1) {
                throw "ERROR: expected exactly one '<name>$NodeName</name>' node in $($fsxPath.Name), found $($found.Count)."
            }
            return [regex]::Replace($Text, $pattern, { param($m) $m.Groups[1].Value + $Value + $m.Groups[3].Value })
        }
        $updated = $text
        $updated = Set-FsxNode $updated 'release'         $release
        $updated = Set-FsxNode $updated 'revision'        $revision
        $updated = Set-FsxNode $updated 'flexsim release' $release
        if ($updated -ne $text) {
            [IO.File]::WriteAllText($fsxPath.FullName, $updated, [Text.UTF8Encoding]::new($false))
            Write-Host "[update-module-version] $($fsxPath.Name): release=$release revision=$revision `"flexsim release`"=$release"
            Write-Host "[update-module-version] REQUIRED: open FlexSim, load this module, and click File > Save Default to regenerate the .t -- the .fsx itself does not ship."
        } else {
            Write-Host "[update-module-version] $($fsxPath.Name) already has release=$release revision=$revision -- no change."
        }
    } else {
        Write-Host "[update-module-version] $($fsxPath.Name) has no release/revision/flexsim-release metadata -- skipping."
    }
} else {
    Write-Host "[update-module-version] no .fsx found under $moduleRoot -- skipping."
}
